---
- name: disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: no
    state: stopped

- name: Install ntp
  apt: pkg=ntp state=latest

- name: Replace config file
  template: src=ntp_conf.j2 dest=/etc/ntp.conf
  notify: restart_ntp

- name: Make ntp start at boot
  systemd:
    name: ntp
    enabled: yes
    masked: no
