# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
#
#  Installs kplex and generates related config file based on variables.
#  Currently only serial input devices and a single output are supported
#  by this role while kplex is capable of much more.
#
#  Usage:
#
#    - role: kplex
#      kplex_serial_inputs:
#        - { device: "/dev/nexus", baud: "4800" }
#        - { device: "/dev/gps", baud: "4800" }
#        - { device: "/dev/ais", baud: "4800" }
#      kplex_output_params:
#        - "device=wlan0"
#        - "port=10110"
#        - "mode=server"
#

---
- name: Download kplex
  get_url: 
    url="{{ kplex_url }}"
    dest="/tmp/{{ kplex_name }}.deb"
  become: no
  
- name: Install kplex
  apt: deb="/tmp/{{ kplex_name }}.deb"

- name: Generate config file
  template: src=kplex_conf.j2 dest=/etc/kplex.conf
  notify: restart_kplex

- name: Generate service file
  template: src=kplex_service.j2 dest=/lib/systemd/system/kplex.service
  notify: restart_kplex

- name: Make kplex start at boot
  systemd:
    name: kplex
    enabled: yes
    masked: no