---
# INSTALLATION
kplex_name: kplex_1.4-1_armhf
kplex_url: http://www.stripydog.com/download/{{ kplex_name }}.deb

# CONFIGURATION

# user is root if needing to make /dev/gps0 in gps forwarding
kplex_user: root
kplex_group: kplex

# Inputs
kplex_serial_inputs: []
kplex_udp_inputs: []

# Server output
kplex_server_transport: tcp
kplex_server_params:
  - "port=10110"
  - "mode=server"

# Marine Traffic forward
kplex_marine_traffic_forwarding_enabled: false
kplex_marine_traffic_address: ""
kplex_marine_traffic_port: ""
kplex_marine_traffic_transport: udp
kplex_marine_traffic_coalesce: "yes"
kplex_marine_traffic_ofilter: "+AIVDM:+AIVDO:-all"

# GPS serial forwarding
kplex_gps_forwarding_enabled: true
kplex_gps_forward_transport: pty
kplex_gps_forward_params:
  - "mode=master"
  - "direction=out"
  - "filename=/dev/gps0"
  - "baud=9600"
  - "owner=root"
  - "group=dialout"
  - "perm=640"

# Logging
kplex_logging_enabled: false
kplex_logging_file: "/home/{{ kplex_user }}/nmea.log"
kplex_logging_timestamp: "s"
