---
- name: Populate service facts
  service_facts:

- name: Download docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/docker-install.sh
    mode: "a+x"
  when: ansible_facts.services['docker.service'] is not defined

- name: Run install script
  shell: /bin/sh /tmp/docker-install.sh
  when: ansible_facts.services['docker.service'] is not defined

- name: Remove temporary file
  file:
    path: /tmp/docker-install.sh
    state: absent

# Fix Docker bug: add containerd as pre-requisite for Docker service, see: https://github.com/docker/for-linux/issues/421
- name: Start Docker after containerd
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "^After="
    line: "After=network-online.target firewalld.service containerd.service"
  notify: Reload systemd
  become: true

- name: Set Docker to auto-start
  service:
    name: docker
    enabled: true
    state: started

- name: add regular user to docker group
  user:
    name: "{{ docker_regular_user }}"
    groups: docker
    append: yes
  become: true

- name: Install pip and deps
  apt:
    name:
      - python3-pip
      - "{{ 'libffi6' if ansible_distribution_major_version | int < 11 else 'libffi7' }}"
      - libffi-dev
    state: latest

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Configure Docker to use custom registry
  block:
    - name: Check if Docker config file exists
      stat:
        path: /etc/docker/daemon.json
      register: docker_config_file
    - name: Create Docker config file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "registry-mirrors": ["{{ docker_custom_registry }}"]
          }
      become: true
      notify: Restart Docker
      when: not docker_config_file.stat.exists
    - name: Check if custom registry is already configured
      lineinfile:
        path: /etc/docker/daemon.json
        regexp: "{{ docker_custom_registry }}"
        state: absent
      check_mode: yes
      changed_when: false
      register: docker_custom_registry_line
    - name: Install jq
      apt:
        name: jq
        state: latest
      become: true
      when: docker_config_file.stat.exists and not docker_custom_registry_line.found
    - name: Add custom registry to Docker config file
      shell: |
        cat /etc/docker/daemon.json | jq '. + {"registry-mirrors": ["{{docker_custom_registry}}"]}' > /etc/docker/daemon2.json
        mv /etc/docker/daemon2.json /etc/docker/daemon.json
      become: true
      notify: Restart Docker
      when: docker_config_file.stat.exists and not docker_custom_registry_line.found
  when: docker_custom_registry != ""
